//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public Nullable<int> MedicalId { get; set; }
        public Nullable<bool> Alert { get; set; }
        public Nullable<bool> IsSend { get; set; }
    
        public virtual Medical Medical { get; set; }
    }
}
