//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPharmacy
    {
        public int Id { get; set; }
        public Nullable<int> IdPharmacy { get; set; }
        public Nullable<int> IdMedical { get; set; }
        public Nullable<int> Quentity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Medical Medical { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
    }
}
